### ISSUE TITLE
Question about TLS in production

### ISSUE THREAD

**Issue by kayotimoteo** [imixs/imixs-cloud#37]
Should I just comment on the first line that I will be able to get Certificates in Production? If yes for me I am not getting it, I used nginx and I got it. He insists on returning the default certificate. Thank you.
![image](https://user-images.githubusercontent.com/18669172/83937166-8830f980-a798-11ea-97c1-ad2f6ec0c34f.png)
In my acme.json I have the following code. with your experience can it take some time in the service and the logo to be verified my certificate?
![image](https://user-images.githubusercontent.com/18669172/83937519-3b9aed80-a79b-11ea-971c-4d0e4c383660.png)

**Comment by letsbuildfoze** [comment]
Can you send me your deployments.yaml?

**Comment by rsoika** [comment]
ok - so far is looks fine for the first step. your acme.yaml file is already created. 

Now I recommand you to use still the staging server in a first place for testing. Otherwise you can run very quick into the Let'sEncrypt rate limits which make things more complicated. LetsEncrypt will block the creation of new certificates after some time which can be seen in the traefik log file. 

Even using the staging letsencrypt server you should see the acme.json file growing. New certificates, even if these are only for testing, should be added to the end of your acme file. 

And yes, it takes some time (seconds, minutes..) until the file is updated.

And again its important that your internet domain is stable. Playing around with ip addresses and dns entries leads into the problem that letsencrypt can not resolve the host correctly. Better test with a new fresh dns entry poining to yoru cluster.

And finally use the /app/whoami/  example for testing.

**Comment by kayotimoteo** [comment]
Thank you very much, it worked, this morning, I published a suggestion for the correction you put on our colleague's topic #35  and he has already released the certificates correctly. Thanks, I'm already a fan of the project and you can count on me.
